image:
  repository: docker.io/postgres
  tag: 17
  pullPolicy: IfNotPresent

service:
  port: 5432

postgres:
  database: "polaris"
  username: "polaris"
  password: "polaris"

persistence:
  size: 8Gi
  storageClass: standard
  keepPolicy: keep