apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: {{ .Values.persistence.keepPolicy | default "delete" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "8Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}